# Generated by Django 3.2.6 on 2021-11-20 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp', models.FileField(blank=True, null=True, upload_to='media/Matrice_de_performance/')),
                ('role', models.CharField(choices=[('initiateur', 'Initiateur'), ('decideur', 'Decideur')], default='decideur', max_length=200)),
                ('nuissance', models.FloatField(default=0, null=True)),
                ('bruit', models.FloatField(default=0, null=True)),
                ('impacts', models.FloatField(default=0, null=True)),
                ('geographique', models.FloatField(default=0, null=True)),
                ('equipement', models.FloatField(default=0, null=True)),
                ('accessibilite', models.FloatField(default=0, null=True)),
                ('climat', models.FloatField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
