# Generated by Django 3.2.6 on 2021-11-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='accessibilite',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='bruit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='climat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='equipement',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='geographique',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='impacts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='nuissance',
            field=models.FloatField(null=True),
        ),
    ]
